apiVersion: v1
kind: Service
metadata:
  name: monservice
spec:
  selector:
    app: nginx-deployment
  type: ClusterIP
  clusterIP: 10.43.5.10
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80